/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:31669519-be9b-44e7-bb90-93a107e872de",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Jqdr3BuoR",
    "aws_user_pools_web_client_id": "279i50ho55laud1sf4vmv1u5sf",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api5d4af517",
            "endpoint": "https://8phnd6lz49.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
